server:
  error:
    include-stacktrace: never

spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:live_coding

  cloud:
    openfeign:
      client:
        config:
          viacep:
            url: https://viacep.com.br/ws/
          opencep:
            url: https://opencep.com/v1/